angular.module("Uelives").controller("relatedIndustryController", function($scope, $rootScope, errorServices, toastServices, localStorageService, config) {
    $scope.input = {}
    
    $scope.select = function(industry) {
        console.log(industry)
        industry.select = !industry.select
    }
    $scope.industries = [{
    	name:"机械机电",
    	select:false
    },{
    	name:"汽车",
    	select:false
    },{
    	name:"电子",
    	select:false
    },{
    	name:"航空",
    	select:false
    },{
    	name:"化工",
    	select:false
    },{
    	name:"IT通讯",
    	select:false
    },{
    	name:"进出口贸易",
    	select:false
    },{
    	name:"互联网",
    	select:false
    },{
    	name:"游戏",
    	select:false
    },{
    	name:"文化传媒",
    	select:false
    },{
    	name:"教育培训",
    	select:false
    },{
    	name:"影视",
    	select:false
    },{
    	name:"字幕",
    	select:false
    },{
    	name:"娱乐",
    	select:false
    },{
    	name:"体育",
    	select:false
    },{
    	name:"医疗健康",
    	select:false
    },{
    	name:"医疗设备",
    	select:false
    },{
    	name:"医药",
    	select:false
    },{
    	name:"食品",
    	select:false
    },{
    	name:"日化",
    	select:false
    },{
    	name:"建筑",
    	select:false
    },{
    	name:"租赁",
    	select:false
    },{
    	name:"法律",
    	select:false
    },{
    	name:"专利",
    	select:false
    },{
    	name:"咨询",
    	select:false
    },{
    	name:"广告",
    	select:false
    },{
    	name:"金融",
    	select:false
    },{
    	name:"财经",
    	select:false
    },{
    	name:"矿产能源",
    	select:false
    },{
    	name:"水利",
    	select:false
    }]
    $scope.save = function(industry) {
        localStorageService.set("industry", industry);
        $rootScope.back();
    }
})